import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { QUESTIONS } from '../../wissenpur/src/data.ts';

const currentDir = dirname(fileURLToPath(import.meta.url));
const outputDir = resolve(currentDir, '../src/generated');
const outputFile = resolve(outputDir, 'questionBank.ts');

const questionBank = QUESTIONS.map((question) => ({
  id: question.id,
  category: question.category,
  correctAnswer: question.correctAnswer,
  optionCount: question.options.length,
}));

const duplicateIds = questionBank
  .map((question) => question.id)
  .filter((id, index, ids) => ids.indexOf(id) !== index);

if (duplicateIds.length > 0) {
  throw new Error(`Duplicate question IDs: ${[...new Set(duplicateIds)].join(', ')}`);
}

for (const question of questionBank) {
  if (!question.id || typeof question.id !== 'string') {
    throw new Error('Every ranked question needs a stable string ID.');
  }

  if (
    !Number.isInteger(question.correctAnswer) ||
    question.correctAnswer < 0 ||
    question.correctAnswer >= question.optionCount
  ) {
    throw new Error(`Invalid correctAnswer for question ${question.id}.`);
  }

  if (question.optionCount !== 4) {
    throw new Error(`Ranked question ${question.id} must have exactly four options.`);
  }
}

await mkdir(outputDir, { recursive: true });
await writeFile(
  outputFile,
  `// Generated by scripts/sync-question-bank.ts. Do not edit manually.\nexport const QUESTION_BANK = ${JSON.stringify(questionBank, null, 2)} as const;\n`,
  'utf8',
);

console.log(`Generated ${questionBank.length} ranked question records.`);
